# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- '*'

pool: 'Default'    # self-hosted agent  

steps:
- checkout: self
  displayName: 'Checkout'

- task: CmdLine@2
  displayName: Build twincat 3 library / run unit tests 
  condition: succeeded()
  inputs:
        failOnStderr: true
        script: '"C:\source\repos\TcRelease\TcBuild.exe" -v "$(System.DefaultWorkingDirectory)\Testing.sln" -p Testing -l Tc3_Testing -o "$(System.DefaultWorkingDirectory)"'
        
- task: PublishTestResults@2
  displayName: Publish results
  condition: or(succeeded(),failed())
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/report*.xml'
    testRunTitle: 'Test-Run'
    buildPlatform: 'Twincat 3'
